apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- image-update.yaml
patches:
- target:
    kind: Deployment
    name: arcc-website
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/votre-username/arcc-website:${IMAGE_TAG}
